import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PPBD 2022 | SDN 1 WATUGEDE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          INFO PPDB <a href="https://ppdb.sdn1watugede.web.id">CALON SISWA</a>
        </h3>

        <p className={styles.description}>
          Tata Cara Pendaftaran <code className={styles.code}>PPDB 2022</code>
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Dokumentasi &rarr;</h2>
            <p>Untuk Pelaksanaan PPDB tahun 2022 di Akhir Bulan Maret</p>
          </a>


      </main>

      <footer className={styles.footer}>
        <a href="https://sdnwatugede.web.id" target="_blank" rel="noopener noreferrer">
          Powered by{"panitia PPDB SD Negeri 1 Watugede"}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
